### ISSUE TITLE
时间进度提示还有点问题

### ISSUE THREAD

**Issue by YingshanDeng** [36Kr-Mobile/KRVideoPlayer#1]
1、播放完毕的时候，时间进度条还没有走完。
2、拖动进度条条，释放后，进度提示会先后退一小段，然后继续走。

解决方案：
1、NSTimer 的 interval 设置小一些，例如：0.1
2、由于设置 slide 的 value 可能小于当前的 value ，所以需要添加一些判断。

**Comment by aidenluo177** [comment]
感谢反馈，会尽快修复

**Comment by aidenluo177** [comment]
感谢反馈，Swift 2版本会修改
