### ISSUE TITLE
有以下建议

### ISSUE THREAD

**Issue by CharlinFeng** [36Kr-Mobile/KRVideoPlayer#10]
1.设置url，可以不立即播放。
2.干掉frame，让autoLayout来布局。

另如果按你的代码，直接写在viewdidLoad是有声音没有界面的。如果让我们自己设置play与autoLayout应该不会有这样的问题哈，

谢谢。

**Comment by aidenluo177** [comment]
感谢反馈，Swift 2版本会修改
