### ISSUE TITLE
播放少一秒

### ISSUE THREAD

**Issue by hzx157** [36Kr-Mobile/KRVideoPlayer#12]
播放少一秒

**Comment by leasontou** [comment]
我这儿也是进度条最后一秒不播放，不知道是少播放了一秒还是进度条显示的有问题

**Comment by hzx157** [comment]
修改两个地方

1.
   self.durationTimer = [NSTimer scheduledTimerWithTimeInterval:0.2 target:self selector:@selector(monitorVideoPlayback) userInfo:nil repeats:YES];
2.
 self.videoControl.progressSlider.maximumValue =floorf(duration);

**Comment by aidenluo177** [comment]
欢迎PR

**Comment by Zhengqi** [comment]
self.videoControl.progressSlider.maximumValue = duration-1;
我是这么改的...
从0开始计数,进度条走20步, 不会在第21个节点(进度条末)停下
