### ISSUE TITLE
pod install之后可定制性弱。

### ISSUE THREAD

**Issue by XenonChau** [36Kr-Mobile/KRVideoPlayer#24]
我需要将`KRVideoPlayerController`中
`@property (nonatomic, strong) KRVideoPlayerControlView *videoControl;`
属性开放。
我想要隐藏关闭按钮。

**Comment by hzx157** [comment]
可以用runtime来解决

**Comment by XenonChau** [comment]
@hzx157 解决问题很简单，简单到利用subviews都能找到。issues的标题是“可定制性弱”。

**Comment by mxpasser** [comment]
我用kvc隐藏的 😄

**Comment by XenonChau** [comment]
作者没有继续更新了，issue close.
