### ISSUE TITLE
打开系统横屏的时候会有问题

### ISSUE THREAD

**Issue by jiazufei** [36Kr-Mobile/KRVideoPlayer#7]
![3df8c3cb-bed6-4f76-95f3-e03431094b0c](https://cloud.githubusercontent.com/assets/3351691/8596595/dc123d6c-2682-11e5-81f0-0036b5ecc55f.png)
目前的情况只能手工锁住controller的竖屏了

**Comment by aidenluo177** [comment]
目前是专为竖屏应用做的，大多数手机应用默认竖屏，不过这个问题会在Swift 2版本解决
